CREATE TABLE Salary (
    SALARY_ID SERIAL PRIMARY KEY,
    EMP_ID VARCHAR(100) NOT NULL REFERENCES Employee(EMP_ID),
    EFFECTIVE_START_DT DATE NOT NULL,
    EFFECTIVE_END_DT DATE,
    SALARY INT NOT NULL,
    UNIQUE (EMP_ID, EFFECTIVE_START_DT)  -- prevent duplicate salary periods
);