CREATE TABLE Location (
    LOCATION_ID SERIAL PRIMARY KEY,
    LOCATION_NAME VARCHAR(100) UNIQUE NOT NULL,
    LOCATION_ADDRESS VARCHAR(255) NOT NULL,
    LOCATION_CITY VARCHAR(100) NOT NULL,
    LOCATION_STATE VARCHAR(2) NOT NULL
);



