CREATE TABLE EmployeeJobHistory (
    HISTORY_ID SERIAL PRIMARY KEY,
    EMP_ID VARCHAR(100) NOT NULL REFERENCES Employee(EMP_ID),
    JOB_TITLE_ID INT NOT NULL REFERENCES JobTitle(JOB_TITLE_ID),
    DEPARTMENT_ID INT NOT NULL REFERENCES Department(DEPARTMENT_ID),
    LOCATION_ID INT NOT NULL REFERENCES Location(LOCATION_ID),
    REPORTING_MANAGER_EMP_ID VARCHAR(100) REFERENCES Manager(EMP_ID),
    START_DT DATE NOT NULL,
    END_DT DATE
);





