
CREATE TABLE Employee (
    EMP_ID VARCHAR(100) PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    HIRE_DT DATE NOT NULL,
    EDUCATION_LEVEL_ID INT NOT NULL REFERENCES EducationLevel(EDUCATION_LEVEL_ID),
    REPORTING_MANAGER_EMP_ID VARCHAR(100) NULL
);





